apiVersion: v1
metadata:
  name: kube-lego
data:
  # modify this to specify your address
  lego.email: "jackmuratore@gmail.com"
  # configure letsencrypt's production api
  lego.url: "https://acme-v01.api.letsencrypt.org/directory"
kind: ConfigMap
