apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - host: jackmuratore.com
    http:
      paths:
      - backend:
          serviceName: jackmuratore
          servicePort: 80
  - host: "*.jackmuratore.com"
    http:
      paths:
      - backend:
          serviceName: jackmuratore
          servicePort: 80
